---
networks:
  t2:
    name: t2
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.90.0/24
  default:
    driver: bridge
  socket_proxy:
    name: socket_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.91.0/24
secrets:
  do_token:
    file: $SECRETSDIR/do_token
services:
  docker-proxy:
    restart: unless-stopped
    image: tecnativa/docker-socket-proxy
    ports:
      - 127.0.0.1:2375:2375
    networks:
      socket_proxy:
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LOG_LEVEL=info
      - EVENTS=1
      - PING=1
      - VERSION=1
      - AUTH=0
      - SECRETS=0
      - POST=1
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1
      - DISTRIBUTION=0
      - EXEC=0
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      - NODES=0
      - PLUGINS=0
      - SERVICES=1
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=1
      - VOLUMES=1
  traefik: 
    restart: unless-stopped
    depends_on:
      - docker-proxy
    image: traefik
    networks:
      t2:
      socket_proxy:
    ports:
      - 80:80
      - 443:443
    volumes:
      - $DOCKERDIR/traefik/rules:/rules
      - $DOCKERDIR/traefik/traefik.yml:/traefik.yml
      - $DOCKERDIR/letsencrypt/acme.json:/etc/letsencrypt/acme.json
      - /var/log/traefik:/logs/
    environment:
      - TZ=$TZ
      - DO_AUTH_TOKEN_FILE=/run/secrets/do_token
    command:
      - --configFile=/traefik.yml
      - --certificatesresolvers.prime-resolver.acme.email=$LE_EMAIL
    secrets:
      - do_token
  nginx:
    restart: unless-stopped
    image: nginx
    depends_on:
      - php
    container_name: nginx
    networks:
      - t2
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - /var/log/nginx:/var/log/nginx
      - $DOCKERDIR/nginx:/etc/nginx
      - $WWWDIR/badger.statbus.space:/var/www/html/badger.statbus.space
      - $WWWDIR/statbus.space:/var/www/html/statbus.space
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx-rtr.entrypoints=websecure
      - traefik.http.routers.nginx-rtr.rule=(Host(`statbus.space`,`badger.statbus.space`))
      - traefik.http.routers.nginx-rtr.tls.certresolver=prime-resolver
      - traefik.http.routers.nginx-rtr.service=nginx-svc
      - traefik.http.services.nginx-svc.loadbalancer.server.port=80
  php:
    restart: unless-stopped
    container_name: php
    build:
      context: $DOCKERDIR/images/php
      dockerfile: dockerfile
    user: $PUID:$PGID
    networks:
      t2:
        ipv4_address: 192.168.90.2
    volumes:
      - /home/atlantaned/tgstation:/tg
      - $WWWDIR/badger.statbus.space:/var/www/html/badger.statbus.space
      - $WWWDIR/statbus.space:/var/www/html/statbus.space