FROM php:8.2-fpm-bullseye
RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y git procps

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod uga+x /usr/local/bin/install-php-extensions && sync 
RUN install-php-extensions pdo_mysql 
RUN install-php-extensions intl 
RUN install-php-extensions gd 
RUN install-php-extensions exif 
RUN install-php-extensions imagick

RUN install-php-extensions @composer